### ISSUE TITLE
DDS output bug in v3.13.0.0

### ISSUE THREAD

**Issue by uncledulgaria** [instrustar-dev/Multi-VirAnalyzer#4]
I have recently purchased an ISDS205X, and installed v3.13.0.0 software.
There is no output from the DDS on fixed frequency waveforms until swept frequency output is activated.
Once this has been done, selecting either fixed frequency or swept frequency output results in swept output.
I have rolled software back to version 3.12.6.0, and this problem is not present, the software works as expected.
I am running Windows10, major release 21H2, with latest quality updates applied.
I have also tested the same ISDS205X unit on a WindowsXP laptop, using version 3.10.12.0, this also works correctly.

I have tried to report this on the InstruStar Users forum, but I cannot, as I do not receive the verification email when I registered.  I have also requested more verification emails using the link on the Security tab of the Settings page. I have waited for around an hour, but the emails have not come.

**Comment by instrustar-dev** [comment]
Thank you very much for your feedback and we will fix this bug as soon as possible

**Comment by instrustar-dev** [comment]
Hello, you feedback bugs, has been fixed, please download this version 3.13.1.0
