### ISSUE TITLE
Wrong frequency displayed

### ISSUE THREAD

**Issue by Van-Shuimu** [instrustar-dev/Multi-VirAnalyzer#5]
I installed last 3.13.1.0 version. When I tried to capture frequency, "measure" bar F displayed twice frequency as real.
On previous 3.12.6.0 version frequency is displayed correctly.
Will attach screenshots, if needed.

**Comment by instrustar-dev** [comment]
Hello, this bug has been fixed, please update 3.13.2.0
https://github.com/instrustar-dev/Multi-VirAnalyzer/releases/tag/V3.13.2.0
